### ISSUE TITLE
Replace usage of document to support server-side-rendering

### ISSUE THREAD

**Issue by janwidmer** [TagCommander/ngx-tag-commander#17]
Hi There,

We are using the ngx-tag-commander within an angular application, which uses Server Side Rendering. When the function `TagCommanderService.addContainer` is getting called during an SSR rendering cycle, the following exception happens: 

```
ReferenceError: document is not defined
    at TagCommanderService.addContainer (/Users/jwidmer/projects/conforama/workspace/js-storefront/conforama-storefront/dist/conforama-storefront-server/main.js:240428:28)
    at TagCommanderModule.setupTracking (/Users/jwidmer/projects/conforama/workspace/js-storefront/conforama-storefront/dist/conforama-storefront-server/main.js:109768:34)
    at new TagCommanderModule (/Users/jwidmer/projects/conforama/workspace/js-storefront/conforama-storefront/dist/conforama-storefront-server/main.js:109764:14)
    at Object.TagCommanderModule_Factory [as factory] (/Users/jwidmer/projects/conforama/workspace/js-storefront/conforama-storefront/dist/conforama-storefront-server/main.js:109788:149)
    at R3Injector.hydrate (/Users/jwidmer/projects/conforama/workspace/js-storefront/conforama-storefront/dist/conforama-storefront-server/main.js:155775:35)
```

Instead of `document.createElement('script')`, maybe the following could used: `this.winRef.nativeWindow.document.createElement('script')` ?

**Comment by michaelcamper** [comment]
Same issue here
